

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hanns
 */
import javax.swing.*;
public class LoginMain extends javax.swing.JFrame {

    /**
     * Creates new form LoginMain
     */
    public LoginMain() {
        initComponents();
        UsernameText.setBackground(new java.awt.Color(0, 0, 0, 1));
        PasswordText.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exit2 = new javax.swing.JLabel();
        panelMenu1 = new panelMenu();
        UsernameIcon = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        UsernameText = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UsernameLine = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        PasswordLine = new javax.swing.JLabel();
        LoginToyourAccountText = new javax.swing.JLabel();
        WelcomeText = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(198, 255, 240));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/437348110_998987741821242_4860051768723652140_n-removebg-preview (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setText("WELCOME TO");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("BookWise Library Management System");

        Exit2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Exit2.setText("x");
        Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(Exit2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(Exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 520, 450));

        panelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/Male User.png"))); // NOI18N
        panelMenu1.add(UsernameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 20, 20));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/Eye.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        panelMenu1.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 21, 19));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/Invisible.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        panelMenu1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 21, 19));

        LoginButton.setBackground(new java.awt.Color(76, 177, 181));
        LoginButton.setText("LOGIN");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginButtonKeyPressed(evt);
            }
        });
        panelMenu1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 80, -1));

        UsernameText.setFont(UsernameText.getFont());
        UsernameText.setForeground(new java.awt.Color(255, 255, 255));
        UsernameText.setBorder(null);
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });
        panelMenu1.add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, -1));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username:");
        panelMenu1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password:");
        panelMenu1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        UsernameLine.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLine.setText("______________________");
        panelMenu1.add(UsernameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 20));

        PasswordText.setFont(PasswordText.getFont());
        PasswordText.setForeground(new java.awt.Color(255, 255, 255));
        PasswordText.setBorder(null);
        PasswordText.setCaretColor(new java.awt.Color(255, 255, 255));
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        panelMenu1.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, -1));

        PasswordLine.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLine.setText("______________________");
        panelMenu1.add(PasswordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, -1));

        LoginToyourAccountText.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        LoginToyourAccountText.setForeground(new java.awt.Color(255, 255, 255));
        LoginToyourAccountText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginToyourAccountText.setText("Login to you Account");
        panelMenu1.add(LoginToyourAccountText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, -1));

        WelcomeText.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeText.setText("WELCOME!");
        panelMenu1.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, -1));

        getContentPane().add(panelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 230, 450));

        setSize(new java.awt.Dimension(737, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        PasswordText.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        PasswordText.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String user=UsernameText.getText();
        String pass=PasswordText.getText();

        if (user.equals("")&&pass.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Username and Password");
        }
        else if (!(user.equals(""))&&pass.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Password..");
        }
        else if (user.equals("")&&!(pass.equals(""))){
            JOptionPane.showMessageDialog(this, "Please Enter Username..");
        }
        else if (user.equals("admin") && pass.equals("pass")){
            new Main().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered

    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void LoginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonKeyPressed

    private void Exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Exit2MouseClicked
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit2;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginToyourAccountText;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PasswordLine;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel UsernameIcon;
    private javax.swing.JLabel UsernameLine;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel disable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private panelMenu panelMenu1;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
