/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Buttons;

/**
 *
 * @author hanns
 */
public class EditStudents extends javax.swing.JPanel {

    /**
     * Creates new form EditStudents
     */
    public EditStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        roundPanel2 = new com.raven.swing.RoundPanel();
        jLabel9 = new javax.swing.JLabel();
        roundPanel1 = new com.raven.swing.RoundPanel();
        roundPanel3 = new com.raven.swing.RoundPanel();

        setBackground(new java.awt.Color(34, 93, 99));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDIT STUDENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 13, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 74, 226, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 126, 226, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, 79, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 178, 99, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Section:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 155, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 178, 120, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 230, 226, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, 99, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 259, 99, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 282, 226, -1));

        roundPanel2.setBackground(new java.awt.Color(76, 177, 181));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 322, -1, -1));

        roundPanel1.setBackground(new java.awt.Color(34, 93, 99));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel3.setBackground(new java.awt.Color(34, 93, 99));
        roundPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        roundPanel1.add(roundPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 370));

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 370));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private com.raven.swing.RoundPanel roundPanel1;
    private com.raven.swing.RoundPanel roundPanel2;
    private com.raven.swing.RoundPanel roundPanel3;
    // End of variables declaration//GEN-END:variables
}
